services:
  # ROS 2 + Gazebo container for Windows with WSL2
  ros2_gazebo:
    image: osrf/ros:humble-desktop-full
    container_name: ros2_gazebo_formation_wsl2
    environment:
      - ROS_DOMAIN_ID=0
      - GAZEBO_MODEL_PATH=/opt/ros/humble/share/gazebo-11/models
      - DISPLAY=host.docker.internal:0.0
      - LIBGL_ALWAYS_INDIRECT=1
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/workspace
    ports:
      - "11311:11311"  # ROS master
      - "14540:14540"  # MAVSDK port 1
      - "14541:14541"  # MAVSDK port 2
      - "14542:14542"  # MAVSDK port 3
    privileged: true
    stdin_open: true
    tty: true
    network_mode: host
    command: >
      bash -c "
        echo '🚀 ROS 2 + Gazebo container starting on Windows with WSL2...' &&
        echo 'Installing additional packages...' &&
        apt-get update &&
        apt-get install -y python3-pip python3-numpy python3-matplotlib &&
        apt-get install -y gazebo libgazebo-dev &&
        pip3 install mavsdk &&
        echo 'Starting Gazebo with GUI...' &&
        export DISPLAY=host.docker.internal:0.0 &&
        export LIBGL_ALWAYS_INDIRECT=1 &&
        export QT_X11_NO_MITSHM=1 &&
        gazebo --verbose /workspace/worlds/px4_formation_flying.world &
        echo 'Starting ROS 2...' &&
        source /opt/ros/humble/setup.bash &&
        echo 'Container ready! Gazebo GUI should be visible on Windows.' &&
        tail -f /dev/null
      "

  # Formation controller container
  formation_controller:
    image: osrf/ros:humble-desktop-full
    container_name: formation_controller_wsl2
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - .:/workspace
    depends_on:
      - ros2_gazebo
    command: >
      bash -c "
        echo '🤖 Formation controller starting on Windows...' &&
        source /opt/ros/humble/setup.bash &&
        cd /workspace &&
        echo 'Building workspace...' &&
        colcon build --packages-select swarm_core &&
        echo 'Formation controller ready!' &&
        tail -f /dev/null
      "
