version: '3.8'

services:
  # ROS 2 + Gazebo container
  ros2_gazebo:
    image: osrf/ros:humble-desktop-full
    container_name: ros2_gazebo_formation
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - GAZEBO_MODEL_PATH=/opt/ros/humble/share/gazebo-11/models
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
    ports:
      - "11311:11311"  # ROS master
      - "14540:14540"  # MAVSDK port 1
      - "14541:14541"  # MAVSDK port 2
      - "14542:14542"  # MAVSDK port 3
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    command: >
      bash -c "
        echo '🚀 ROS 2 + Gazebo container starting...' &&
        echo 'Installing additional packages...' &&
        apt-get update &&
        apt-get install -y python3-pip python3-numpy python3-matplotlib &&
        pip3 install mavsdk &&
        echo 'Starting Gazebo...' &&
        gazebo --verbose /opt/ros/humble/share/gazebo-11/worlds/empty.world &
        echo 'Starting ROS 2...' &&
        source /opt/ros/humble/setup.bash &&
        echo 'Container ready! Use docker exec to run commands.' &&
        tail -f /dev/null
      "

  # Formation controller container
  formation_controller:
    image: osrf/ros:humble-desktop-full
    container_name: formation_controller
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - .:/workspace
    depends_on:
      - ros2_gazebo
    command: >
      bash -c "
        echo '🤖 Formation controller starting...' &&
        source /opt/ros/humble/setup.bash &&
        cd /workspace &&
        echo 'Building workspace...' &&
        colcon build --packages-select swarm_core &&
        echo 'Formation controller ready!' &&
        tail -f /dev/null
      "
